name: CI
run-name: ${{ github.actor }} is deploying DevResultsTools
env:
  ARTIFACT_NAME: PowerShell.DevResultTools.InstanceExport
on:
  - push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Generating code signing cert and signing Add-Signature ps script
        env:
          PFX_CONTENT: ${{ secrets.BASE64_PFX_CONTENT }}
        run: |
          cd ./InstanceExport/PowerShell;
          $pfxPath = Join-Path -Path $env:RUNNER_TEMP -ChildPath "cert.pfx";
          $encodedBytes = [System.Convert]::FromBase64String($env:PFX_CONTENT);
          Set-Content $pfxPath -Value $encodedBytes -AsByteStream;
          $cert = Import-PfxCertificate -FilePath ./cert.pfx -CertStoreLocation Cert:\LocalMachine\My
          Set-AuthenticodeSignature Add-Signature.ps1 $cert
        shell: pwsh
      - name: Adding self signature to InstanceExport script
        run: |
          cd ./InstanceExport/PowerShell;
          ./Add-Signature.ps1 -file InstanceExport.ps1
        shell: pwsh
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./InstanceExport/PowerShell/InstanceExport.ps1
